from typing import Any, Callable, Dict
from terminal_zero.core.state import CommandContext, CommandResult
from terminal_zero.commands.posix import (
    cmd_pwd,
    cmd_cd,
    cmd_ls,
    cmd_ll,
    cmd_cat,
    cmd_head,
    cmd_tail,
    cmd_grep,
    cmd_find,
    cmd_chmod,
    cmd_ps,
    cmd_kill,
    cmd_ip,
    cmd_ss,
    cmd_ping,
    cmd_echo,
    cmd_tree,
    cmd_append,
)
from terminal_zero.commands.diegetic import (
    cmd_decrypt,
    cmd_repair_buffer,
    cmd_phoenix_daemon,
    cmd_phoenix_ctl,
    cmd_apollo_net,
    cmd_sync,
    cmd_reboot,
    cmd_man,
    cmd_restore,
    cmd_help,
    cmd_note,
    cmd_feedback,
    cmd_taskctl,
    cmd_todo,
    cmd_tasks,
    cmd_manuals,
    cmd_docs,
    cmd_fieldguide,
    cmd_cards,
    cmd_debriefs,
    cmd_lore,
    cmd_triage_process,
    cmd_triage_sector,
    cmd_triage_interface,
    cmd_triage_service,
)


def build_command_table() -> Dict[str, Callable[[CommandContext, list], CommandResult]]:
    return {
        "pwd": cmd_pwd,
        "cd": cmd_cd,
        "ls": cmd_ls,
        "ll": cmd_ll,
        "cat": cmd_cat,
        "head": cmd_head,
        "tail": cmd_tail,
        "grep": cmd_grep,
        "find": cmd_find,
        "chmod": cmd_chmod,
        "man": cmd_man,
        "help": cmd_help,
        "?": cmd_help,
        "decrypt": cmd_decrypt,
        "apollo-diagnostics": cmd_decrypt,
        "sync": cmd_sync,
        "tree": cmd_tree,
        "ps": cmd_ps,
        "kill": cmd_kill,
        "ip": cmd_ip,
        "ss": cmd_ss,
        "ping": cmd_ping,
        "echo": cmd_echo,
        "repair_buffer": cmd_repair_buffer,
        "phoenix_ctl": cmd_phoenix_ctl,
        "phoenix_daemon": cmd_phoenix_daemon,
        "apollo-net": cmd_apollo_net,
        "restore": cmd_restore,
        "reboot": cmd_reboot,
        "reset": cmd_reboot,
        "restart": cmd_reboot,
        "note": cmd_note,
        "feedback": cmd_feedback,
        "taskctl": cmd_taskctl,
        "todo": cmd_todo,
        "tasks": cmd_tasks,
        "manuals": cmd_manuals,
        "docs": cmd_docs,
        "fieldguide": cmd_fieldguide,
        "cards": cmd_cards,
        "debriefs": cmd_debriefs,
        "lore": cmd_lore,
        "append": cmd_append,
        "triage_process": cmd_triage_process,
        "triage_sector": cmd_triage_sector,
        "triage_interface": cmd_triage_interface,
        "triage_service": cmd_triage_service,
    }


COMMAND_TABLE = build_command_table()

__all__ = [
    "build_command_table",
    "COMMAND_TABLE",
]
